- scripts/setup_env.js
- src/app/auth/login/login.component.ts
- src/app/core/services/core/api.service.ts
This reverts commit 712d0391c086641a2b514906159198f43c9f1471.
> Revert "Add loggers for debugging login issue (#8)"

- src/app/shared/components/qbd/configuration/configuration-select-field/configuration-select-field.component.html
Dropdowns are breaking, label, value both going in payload, for QBD too, this fixed the label.
> Configuration Select Field : Fix (Options - Label)

- src/app/shared/components/apps/configuration-select-field/configuration-select-field.component.html
> Fix for select field

- src/app/integrations/si/main/dashboard/dashboard.component.html
- Shimmers Fix for Dashboard Failed Expense
> CSS Fixes : Shimmers Fix (Dashboard)

- src/app/shared/components/si/configuration/configuration-advanced-settings/configuration-advanced-settings.component.ts
https://github.com/fylein/fyle-integrations-settings-app/assets/116036738/1a4f50f0-aa1c-4435-b514-b261e172eca5
> Bug fix for Schedule Automatic Export

- src/app/integrations/si/main/dashboard/dashboard.component.html
- src/app/integrations/si/main/dashboard/dashboard.component.scss
> Fix for Dashboard Width Email [Sage Intacct Redesign]

- src/app/integrations/sage300/sage300-shared/sage300-import-settings/sage300-import-settings.component.html
- src/app/integrations/sage300/sage300-shared/sage300-import-settings/sage300-import-settings.component.ts
- src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
- src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.scss
- src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.spec.ts
- src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.ts
- src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
- src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.ts
- src/app/shared/shared.module.ts
> configuration confirmation dialog construction

- src/app/core/models/sage300/sage300-configuration/sage300-import-settings.model.ts
- src/app/integrations/sage300/sage300-shared/sage300-import-settings/sage300-import-settings.component.html
- src/app/integrations/sage300/sage300-shared/sage300-import-settings/sage300-import-settings.component.ts
- src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
- src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.scss
- src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.spec.ts
- src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.ts
- src/app/shared/components/configuration/configuration-custom-field-creation-dialog/configuration-custom-field-creation-dialog.component.html
- src/app/shared/components/configuration/configuration-custom-field-creation-dialog/configuration-custom-field-creation-dialog.component.scss
- src/app/shared/components/configuration/configuration-custom-field-creation-dialog/configuration-custom-field-creation-dialog.component.spec.ts
- src/app/shared/components/configuration/configuration-custom-field-creation-dialog/configuration-custom-field-creation-dialog.component.ts
- src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
- src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.ts
- src/app/shared/shared.module.ts
configuration custom field creation dialog
> configuration custom field creation dialog construction

- src/app/core/models/db/accounting-export.model.ts
- src/app/shared/components/export-log/export-log-table/export-log-table.component.ts
- will raise review request for #286 for this pr changes.
> Sage300 Export Log - 3.1 [PR Comments (Model Fixes: Table)]

- src/app/integrations/si/main/dashboard/dashboard.component.html
- src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.html
https://app.clickup.com/t/86cu5aa6a
> [IS] : Sage Redesign Sub Heading Text Update

- src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.html
> Testing Fixes : Post Onboarding

- src/app/core/services/common/export-log.service.ts
- src/app/core/services/common/skip-export.service.ts
- src/app/integrations/business-central/business-central-shared/business-central-advanced-settings/business-central-advanced-settings.component.ts
- src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.ts
- src/app/integrations/sage300/sage300-shared/sage300-advanced-settings/sage300-advanced-settings.component.ts
- src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.ts
> Skip Export: Delete Expense Filter fix

- run.sh
- scripts/setup_env.js
- src/app/auth/login/login.component.ts
- src/app/core/models/misc/token.model.ts
- src/app/core/services/common/api.service.ts
- src/app/core/services/common/auth.service.ts
- src/app/core/services/common/helper.service.ts
- src/app/integrations/landing/landing.component.html
- src/app/integrations/landing/landing.component.ts
This reverts commit 4a413171cc5902cf3d7b0c6a8b2f468b883b5991.
> Revert "Support for different clusters (#468)"

- src/app/integrations/xero/xero-onboarding/xero-onboarding-done/xero-onboarding-done.component.html
- src/app/integrations/xero/xero-onboarding/xero-onboarding-done/xero-onboarding-done.component.ts
> Xero Onboarding done coding

- src/app/integrations/business-central/business-central-main/business-central-dashboard/business-central-dashboard.component.ts
- src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.html
- src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-skip-export-log/intacct-skip-export-log.component.html
- src/app/integrations/qbd/main/dashboard/dashboard.component.ts
- src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.html
- src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.ts
- src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-skipped-export-log/qbo-skipped-export-log.component.html
- src/app/integrations/xero/xero-main/xero-export-log/xero-complete-export-log/xero-complete-export-log.component.html
- src/app/integrations/xero/xero-main/xero-export-log/xero-skipped-export-log/xero-skipped-export-log.component.html
- src/app/shared/components/input/search/search.component.ts
This reverts commit d465211ac0eb12f902e5f9eceda1bb920fc0d835.
> Revert "Fix calendar close issue on date selection (#684)"

- src/app/core/models/enum/enum.model.ts
- src/app/core/services/common/dashboard.service.ts
- src/app/core/services/common/export-log.service.ts
- src/app/integrations/netsuite/netsuite-main/netsuite-configuration/netsuite-configuration.component.html
- src/app/integrations/netsuite/netsuite-main/netsuite-configuration/netsuite-configuration.component.ts
- src/app/integrations/netsuite/netsuite-main/netsuite-dashboard/netsuite-dashboard.component.html
- src/app/integrations/netsuite/netsuite-main/netsuite-dashboard/netsuite-dashboard.component.ts
- src/app/integrations/netsuite/netsuite-main/netsuite-export-log/netsuite-complete-export-logs/netsuite-complete-export-logs.component.ts
- src/app/integrations/netsuite/netsuite-main/netsuite-main.component.ts
- src/app/integrations/netsuite/netsuite-main/netsuite-mapping/netsuite-base-mapping/netsuite-base-mapping.component.html
- src/app/integrations/netsuite/netsuite-main/netsuite-mapping/netsuite-base-mapping/netsuite-base-mapping.component.ts
- src/app/integrations/netsuite/netsuite-main/netsuite-mapping/netsuite-mapping.component.html
- src/app/integrations/netsuite/netsuite-main/netsuite-mapping/netsuite-mapping.component.ts
> netsuite configuration page set up

- src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
- src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
- Fix for Netsuite dateOptions for CCC
> Fix for dateOptions: Export Settings

- src/app/core/models/common/advanced-settings.model.ts
- Added support for boolean, for all integrations, sage intacct support is alread present
> BOOLEAN for skip export, for all integrations except Sage Intacct

- src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.html
- src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
- src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.scss
https://github.com/fylein/fyle-integrations-app/assets/116036738/0f5a9f41-bf7c-4ef1-8fd4-c3c825011018
> Clear Icon for Payment Sync

- src/app/core/models/common/export-settings.model.ts
- src/app/core/models/enum/enum.model.ts
- src/app/core/models/intacct/intacct-configuration/export-settings.model.ts
- src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
- src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.html
- src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
- src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.ts
This reverts commit ce6b051fba73f1d3b23edea5652ea97ecce2c8d1.
> Revert "feat: add advanced search to ccc export settings fields in netsuite

- src/app/branding/c1-contents-config.ts
- src/app/branding/fyle-contents-config.ts
- src/app/core/models/branding/content-configuration.model.ts
- src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
This PR contains the changes to place skip export in advanced settings of qbd direct integrations
Please add link here
> feat: qbd direct integrations advanced settings skip export

- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.ts
QBD Direct Integrations Import settings save changes
https://app.clickup.com/t/86cwmdtdd
> feat: qbd direct import settings save changes

- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.html
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-mapping.component.html
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-mapping.component.ts
qbd direct post onboarding mapping page implementation
https://app.clickup.com/t/86cwmdru4
> feat: qbd direct post onboarding mapping page implementation

- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.html
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-export-log-routing.module.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-export-log.component.html
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-export-log.component.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-skipped-export-log/qbd-direct-skipped-export-log.component.html
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-skipped-export-log/qbd-direct-skipped-export-log.component.spec.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-skipped-export-log/qbd-direct-skipped-export-log.component.ts
qbd direct successful export log page settings
https://app.clickup.com/t/86cwmduta
> feat: qbd direct successfull export log page settings

- src/app/branding/c1-branding-config.ts
- src/app/branding/c1-contents-config.ts
- src/app/branding/fyle-branding-config.ts
- src/app/branding/fyle-contents-config.ts
- src/app/core/models/branding/content-configuration.model.ts
- src/app/core/models/branding/demo-video.model.ts
- src/app/core/models/branding/kb-article.model.ts
- src/app/core/models/common/advanced-settings.model.ts
- src/app/core/models/enum/enum.model.ts
- src/app/core/models/qbd-direct/db/qbd-direct-destination-attribuite.model.ts
- src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
- src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-export-settings.model.ts
- src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-import-settings.model.ts
- src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-import-settings.service.ts
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.html
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.ts
configuration pages html and ts fix
https://app.clickup.com/t/86cwpmtxe
> feat: Configuration pages html and ts fix

- src/app/shared/components/configuration/configuration-custom-field-creation-dialog/configuration-custom-field-creation-dialog.component.ts
> fix: restrict creation of custom field with merchant name

- src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.html
- src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.ts
> feat: Allow single credit JE only for US orgs

- src/app/branding/c1-contents-config.ts
- src/app/branding/fyle-contents-config.ts
- src/app/core/models/enum/enum.model.ts
- src/app/core/services/common/accounting-export.service.ts
- src/app/core/services/common/dashboard.service.ts
- src/app/core/services/common/export-log.service.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-mapping.component.ts
qbd direct api changes for dashboard, export settings and mapping pages
https://app.clickup.com/t/86cwpmtyq
user-attachments/assets/1ce153f2-57f8-45fb-b15e-0ed9e8450b35">
> feat: qbd direct api changes for dashboard, export settings and mapping pages

- src/app/branding/c1-contents-config.ts
- src/app/branding/fyle-contents-config.ts
- src/app/core/models/common/advanced-settings.model.ts
- src/app/core/models/enum/enum.model.ts
- src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
- src/app/core/services/common/accounting-export.service.ts
- src/app/core/services/common/dashboard.service.ts
- src/app/core/services/common/export-log.service.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-mapping.component.ts
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
- src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.ts
qbd direct advanced settings Api testing changes
https://app.clickup.com/t/86cwpmtxr
> feat: qbd direct advanced settings Api testing changes

- src/app/branding/c1-contents-config.ts
- src/app/branding/fyle-contents-config.ts
- src/app/core/models/common/advanced-settings.model.ts
- src/app/core/models/enum/enum.model.ts
- src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
- src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-import-settings.model.ts
- src/app/core/services/common/accounting-export.service.ts
- src/app/core/services/common/dashboard.service.ts
- src/app/core/services/common/export-log.service.ts
- src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-import-settings.service.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-mapping.component.ts
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.ts
- src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.ts
Qbd direct import settings testing with api changes
https://app.clickup.com/t/86cwpmtxm
> feat: Qbd direct import settings testing with api changes

- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
feat: qbd direct connector data sync up ts changes
https://app.clickup.com/t/86cwzcepk
> feat: qbd direct connector data sync up ts changes

- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.ts
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
- src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.ts
feat: qbd direct connector download file ts changes
https://app.clickup.com/t/86cwzcepa
> feat: qbd direct connector download file ts changes

- src/app/integrations/landing/landing.component.ts
https://app.clickup.com/t/86cx5t0wf
> fix: update orgs to hide business central beta badge from

- src/app/core/models/netsuite/netsuite-configuration/netsuite-advanced-settings.model.ts
- hide options for memo c1
- app.clickup.com/t/anishnetsuitec1
> fix: fix memo options for C1

- .github/workflows/c1-staging-deployment.yml
- .github/workflows/qa-deployment.yml
- .github/workflows/staging-deployment.yml
> chore: deploy to all staging envs

- src/app/app.component.ts
- src/app/auth/login/login.component.ts
https://app.clickup.com/t/86cy5xqhn
> fix: move login event handlers from app to login component

- src/app/core/interceptor/jwt.interceptor.spec.ts
> fix: Update to dummy token in tests

- src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
- src/app/shared/components/menu/main-menu/main-menu.component.ts
figma size alignments
https://app.clickup.com/1864988/v/l/li/901607316229
> fix: figma size alignments

- src/app/core/guard/qbo-token.guard.ts
fix-qbo-health-guard
https://app.clickup.com/1864988/v/l/6-901607316229-1
> fix: qbo-health-guard issue

- src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.ts
> fix: API url in re connection

- src/app/core/models/common/advanced-settings.model.ts
- src/app/core/models/qbo/qbo-configuration/qbo-advanced-setting.model.ts
- src/app/core/services/common/accounting-export.service.ts
- src/app/core/services/common/export-log.service.ts
- src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.ts
- src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.ts
- src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.ts
- src/app/integrations/qbo/qbo.fixture.ts
- src/app/integrations/xero/xero-main/xero-dashboard/xero-dashboard.component.ts
- src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.ts
- src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.ts
- src/app/shared/components/configuration/configuration-schedule-export/configuration-schedule-export.component.html
- src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.html
- src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
> feat: Real-time exports, phase 2 - QBO

- src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
- src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.ts
https://app.clickup.com/t/86cz6aap1
> fix(e2e): add aria attributes to intacct import settings switches

- src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
- src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.scss
https://app.clickup.com/t/86czv4uxp
> fix: intacct dropdown menu alignment fix

- src/app/core/services/netsuite/netsuite-configuration/netsuite-export-settings.service.ts
> fix: journal entry name option default for c1

- src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
https://app.clickup.com/t/86d01wkgv
> fix: dashboard progress bar and count
